blank_issues_enabled: false
contact_links:
  - name: 📖 Docker-Android Documentation
    url: https://github.com/budtmo/docker-android
    about: Please read the whole project README before filling out an issue.
